const data = {
  users: [
    {
      name: 'Simran',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Simran',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'The 10X Rule',
      category: 'Psychology',
      image: '/images/b1.jpg',
      price: 120,
      countInStock: 10,
      author: 'Grant Cardone',
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: 'Art of Exceptional Living',
      category: 'Psychology',
      image: '/images/b2.jpg',
      price: 100,
      countInStock: 20,
      author: 'Jim Rohn',
      rating: 4.0,
      numReviews: 10,
    },
    {
      name: 'Atomic Habits',
      category: 'Psychology',
      image: '/images/b3.jpg',
      price: 220,
      countInStock: 0,
      author: 'James Clear',
      rating: 4.8,
      numReviews: 17,
    },
    {
      name: 'Hooked',
      category: 'Literature',
      image: '/images/b4.jpg',
      price: 78,
      countInStock: 15,
      author: 'Nir Eyal',
      rating: 4.5,
      numReviews: 14,
    },
    {
      name: 'Ikigai',
      category: 'Literature',
      image: '/images/b5.jpg',
      price: 65,
      countInStock: 5,
      author: 'Hector Garcia',
      rating: 4.5,
      numReviews: 10,
    },
    {
      name: 'Thinking, Fast and Slow',
      category: 'Literature',
      image: '/images/b6.jpg',
      price: 139,
      countInStock: 12,
      author: 'Daniel Kahneman',
      rating: 4.5,
      numReviews: 15,
    },
  ],
};
export default data;